# Generated by Django 3.2.7 on 2021-09-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_app', '0002_alter_mark_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
