# Generated by Django 3.2.7 on 2021-09-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat_app', '0003_alter_mark_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='cat',
            field=models.CharField(max_length=20),
        ),
    ]
